import { PokemonTypes } from '~/types/pokemonTypes.types'

/**
 * 타입 상성 배율.
 * - 0   : 효과 없음 (0배)
 * - 0.5 : 효과가 별로 (0.5배)
 * - 1   : 보통 (1배, 표에서는 빈 칸)
 * - 2   : 효과가 굉장 (2배)
 */
export type EffectivenessValue = 0 | 0.5 | 1 | 2

/**
 * 공격 타입 → 방어 타입별 상성 배율 매트릭스 (18×18).
 *
 * `TYPE_EFFECTIVENESS_CHART[공격타입][방어타입]` 형태로 조회한다.
 * 기존 `TypeEffectivenessTable.component.tsx`에 하드코딩돼 있던 18×18 표를
 * 데이터로 추출한 것이며, desktop/mobile이 동일 데이터를 공유한다.
 *
 * @see src/container/{desktop,mobile}/typeEffectiveness/typeEffectiveness.table
 */
export const TYPE_EFFECTIVENESS_CHART: Record<
  PokemonTypes,
  Record<PokemonTypes, EffectivenessValue>
> = {
  [PokemonTypes.NORMAL]: {
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.FIRE]: 1,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.GRASS]: 1,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.ROCK]: 0.5,
    [PokemonTypes.GHOST]: 0,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.STEEL]: 0.5,
    [PokemonTypes.FAIRY]: 1,
  },
  [PokemonTypes.FIRE]: {
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.FIRE]: 0.5,
    [PokemonTypes.WATER]: 0.5,
    [PokemonTypes.GRASS]: 2,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.ICE]: 2,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.BUG]: 2,
    [PokemonTypes.ROCK]: 0.5,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.DRAGON]: 0.5,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.STEEL]: 2,
    [PokemonTypes.FAIRY]: 1,
  },
  [PokemonTypes.WATER]: {
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.FIRE]: 2,
    [PokemonTypes.WATER]: 0.5,
    [PokemonTypes.GRASS]: 0.5,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.GROUND]: 2,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.ROCK]: 2,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.DRAGON]: 0.5,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.STEEL]: 1,
    [PokemonTypes.FAIRY]: 1,
  },
  [PokemonTypes.GRASS]: {
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.FIRE]: 0.5,
    [PokemonTypes.WATER]: 2,
    [PokemonTypes.GRASS]: 0.5,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.POISON]: 0.5,
    [PokemonTypes.GROUND]: 2,
    [PokemonTypes.FLYING]: 0.5,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.BUG]: 0.5,
    [PokemonTypes.ROCK]: 2,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.DRAGON]: 0.5,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.STEEL]: 0.5,
    [PokemonTypes.FAIRY]: 1,
  },
  [PokemonTypes.ELECTRIC]: {
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.FIRE]: 1,
    [PokemonTypes.WATER]: 2,
    [PokemonTypes.GRASS]: 0.5,
    [PokemonTypes.ELECTRIC]: 0.5,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.GROUND]: 0,
    [PokemonTypes.FLYING]: 2,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.ROCK]: 1,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.DRAGON]: 0.5,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.STEEL]: 1,
    [PokemonTypes.FAIRY]: 1,
  },
  [PokemonTypes.ICE]: {
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.FIRE]: 0.5,
    [PokemonTypes.WATER]: 0.5,
    [PokemonTypes.GRASS]: 2,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.ICE]: 0.5,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.GROUND]: 2,
    [PokemonTypes.FLYING]: 2,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.ROCK]: 1,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.DRAGON]: 2,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.STEEL]: 0.5,
    [PokemonTypes.FAIRY]: 1,
  },
  [PokemonTypes.FIGHTING]: {
    [PokemonTypes.NORMAL]: 2,
    [PokemonTypes.FIRE]: 1,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.GRASS]: 1,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.ICE]: 2,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.POISON]: 0.5,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.FLYING]: 0.5,
    [PokemonTypes.PSYCHIC]: 0.5,
    [PokemonTypes.BUG]: 0.5,
    [PokemonTypes.ROCK]: 2,
    [PokemonTypes.GHOST]: 0,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.DARK]: 2,
    [PokemonTypes.STEEL]: 2,
    [PokemonTypes.FAIRY]: 0.5,
  },
  [PokemonTypes.POISON]: {
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.FIRE]: 1,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.GRASS]: 2,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.POISON]: 0.5,
    [PokemonTypes.GROUND]: 0.5,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.ROCK]: 0.5,
    [PokemonTypes.GHOST]: 0.5,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.STEEL]: 0,
    [PokemonTypes.FAIRY]: 2,
  },
  [PokemonTypes.GROUND]: {
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.FIRE]: 2,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.GRASS]: 0.5,
    [PokemonTypes.ELECTRIC]: 2,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.POISON]: 2,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.FLYING]: 0,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.BUG]: 0.5,
    [PokemonTypes.ROCK]: 2,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.STEEL]: 2,
    [PokemonTypes.FAIRY]: 1,
  },
  [PokemonTypes.FLYING]: {
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.FIRE]: 1,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.GRASS]: 2,
    [PokemonTypes.ELECTRIC]: 0.5,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.FIGHTING]: 2,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.BUG]: 2,
    [PokemonTypes.ROCK]: 0.5,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.STEEL]: 0.5,
    [PokemonTypes.FAIRY]: 1,
  },
  [PokemonTypes.PSYCHIC]: {
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.FIRE]: 1,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.GRASS]: 1,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.FIGHTING]: 2,
    [PokemonTypes.POISON]: 2,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.PSYCHIC]: 0.5,
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.ROCK]: 1,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.DARK]: 0,
    [PokemonTypes.STEEL]: 0.5,
    [PokemonTypes.FAIRY]: 1,
  },
  [PokemonTypes.BUG]: {
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.FIRE]: 0.5,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.GRASS]: 2,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.FIGHTING]: 0.5,
    [PokemonTypes.POISON]: 0.5,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.FLYING]: 0.5,
    [PokemonTypes.PSYCHIC]: 2,
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.ROCK]: 1,
    [PokemonTypes.GHOST]: 0.5,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.DARK]: 2,
    [PokemonTypes.STEEL]: 0.5,
    [PokemonTypes.FAIRY]: 0.5,
  },
  [PokemonTypes.ROCK]: {
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.FIRE]: 2,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.GRASS]: 1,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.ICE]: 2,
    [PokemonTypes.FIGHTING]: 0.5,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.GROUND]: 0.5,
    [PokemonTypes.FLYING]: 2,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.BUG]: 2,
    [PokemonTypes.ROCK]: 1,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.STEEL]: 0.5,
    [PokemonTypes.FAIRY]: 1,
  },
  [PokemonTypes.GHOST]: {
    [PokemonTypes.NORMAL]: 0,
    [PokemonTypes.FIRE]: 1,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.GRASS]: 1,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.PSYCHIC]: 2,
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.ROCK]: 1,
    [PokemonTypes.GHOST]: 2,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.DARK]: 0.5,
    [PokemonTypes.STEEL]: 1,
    [PokemonTypes.FAIRY]: 1,
  },
  [PokemonTypes.DRAGON]: {
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.FIRE]: 1,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.GRASS]: 1,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.ROCK]: 1,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.DRAGON]: 2,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.STEEL]: 0.5,
    [PokemonTypes.FAIRY]: 0,
  },
  [PokemonTypes.DARK]: {
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.FIRE]: 1,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.GRASS]: 1,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.FIGHTING]: 0.5,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.PSYCHIC]: 2,
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.ROCK]: 1,
    [PokemonTypes.GHOST]: 2,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.DARK]: 0.5,
    [PokemonTypes.STEEL]: 1,
    [PokemonTypes.FAIRY]: 0.5,
  },
  [PokemonTypes.STEEL]: {
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.FIRE]: 0.5,
    [PokemonTypes.WATER]: 0.5,
    [PokemonTypes.GRASS]: 1,
    [PokemonTypes.ELECTRIC]: 0.5,
    [PokemonTypes.ICE]: 2,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.ROCK]: 2,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.STEEL]: 0.5,
    [PokemonTypes.FAIRY]: 2,
  },
  [PokemonTypes.FAIRY]: {
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.FIRE]: 0.5,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.GRASS]: 1,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.FIGHTING]: 2,
    [PokemonTypes.POISON]: 0.5,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.ROCK]: 1,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.DRAGON]: 2,
    [PokemonTypes.DARK]: 2,
    [PokemonTypes.STEEL]: 0.5,
    [PokemonTypes.FAIRY]: 1,
  },
}

/** 공격 타입 순서 (표의 행/열 순서 = enum 정의 순서) */
export const TYPE_ORDER: PokemonTypes[] = Object.values(PokemonTypes)
