export enum PokemonTypes {
  NORMAL = '노말',
  FIRE = '불꽃',
  WATER = '물',
  GRASS = '풀',
  ELECTRIC = '전기',
  ICE = '얼음',
  FIGHTING = '격투',
  POISON = '독',
  GROUND = '땅',
  FLYING = '비행',
  PSYCHIC = '에스퍼',
  BUG = '벌레',
  ROCK = '바위',
  GHOST = '고스트',
  DRAGON = '드래곤',
  DARK = '악',
  STEEL = '강철',
  FAIRY = '페어리',
}

export enum TypesColor {
  NORMAL = '#ddddcc',
  FIRE = '#f9cfb3',
  WATER = '#c6d4f9',
  GRASS = '#cbe9be',
  ELECTRIC = '#fcedb4',
  ICE = '#d7efef',
  FIGHTING = '#e6b3b0',
  POISON = '#dab9da',
  GROUND = '#f3e7c6',
  FLYING = '#ddd4f9',
  PSYCHIC = '#fcc0d1',
  BUG = '#dde3b0',
  ROCK = '#e3dab6',
  GHOST = '#c8c0d7',
  DRAGON = '#c8b6fd',
  DARK = '#c7c0ba',
  STEEL = '#B8Be3e3ed8D0',
  FAIRY = '#f8d8df',
}

export enum TypeCompatibility {
  STRONG = 1,
  WEAK = -1,
  ZERO = 0,
}

export enum IconColor {
  NORMAL = '#f5f5d3',
  FIRE = '#ffc59b',
  WATER = '#bbcffe',
  GRASS = '#ddffcd',
  ELECTRIC = '#fff4ca',
  ICE = '#ddfafa',
  FIGHTING = '#ffaca7',
  POISON = '#ffb2ff',
  GROUND = '#fdf0cf',
  FLYING = '#e2d8ff',
  PSYCHIC = '#ffc1d4',
  BUG = '#f8ffbb',
  ROCK = '#fff0b0',
  GHOST = '#dcc7ff',
  DRAGON = '#ba9dff',
  DARK = '#f3d3be',
  STEEL = '#f3f3ff',
  FAIRY = '#ffd7e0',
}

export enum EngTypes {
  NORMAL = 'normal',
  FIRE = 'fire',
  WATER = 'water',
  GRASS = 'grass',
  ELECTRIC = 'electric',
  ICE = 'ice',
  FIGHTING = 'fighting',
  POISON = 'poison',
  GROUND = 'ground',
  FLYING = 'flying',
  PSYCHIC = 'psychic',
  BUG = 'bug',
  ROCK = 'rock',
  GHOST = 'ghost',
  DRAGON = 'dragon',
  DARK = 'dark',
  STEEL = 'steel',
  FAIRY = 'fairy',
}
