import styled from 'styled-components'

const TypeEffectivenessContainer = () => {
  return (
    <Div>
      <article className="type-effectiveness-table">
        <table>
          <thead>
            <tr>
              <th></th>
              <th>Normal</th>
              <th>Fire</th>
              <th>Water</th>
              <th>Grass</th>
              <th>Electric</th>
              <th>Ice</th>
              <th>Fighting</th>
              <th>Poison</th>
              <th>Ground</th>
              <th>Flying</th>
              <th>Psychic</th>
              <th>Bug</th>
              <th>Rock</th>
              <th>Ghost</th>
              <th>Dragon</th>
              <th>Dark</th>
              <th>Steel</th>
              <th>Fairy</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th>Normal</th>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td>△</td>
              <td>x</td>
              <td></td>
              <td></td>
              <td>△</td>
              <td></td>
            </tr>
            <tr>
              <th>Fire</th>
              <td></td>
              <td>△</td>
              <td>△</td>
              <td>◎</td>
              <td></td>
              <td>◎</td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td>◎</td>
              <td>△</td>
              <td></td>
              <td>△</td>
              <td></td>
              <td>◎</td>
              <td></td>
            </tr>
            <tr>
              <th>Water</th>
              <td></td>
              <td>◎</td>
              <td>△</td>
              <td>△</td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td>◎</td>
              <td></td>
              <td></td>
              <td></td>
              <td>◎</td>
              <td></td>
              <td>△</td>
              <td></td>
              <td></td>
              <td></td>
            </tr>
            <tr>
              <th>Grass</th>
              <td></td>
              <td>△</td>
              <td>◎</td>
              <td>△</td>
              <td></td>
              <td></td>
              <td></td>
              <td>△</td>
              <td>◎</td>
              <td>△</td>
              <td></td>
              <td>△</td>
              <td>◎</td>
              <td></td>
              <td>△</td>
              <td></td>
              <td>△</td>
              <td></td>
            </tr>
            <tr>
              <th>Electric</th>
              <td></td>
              <td></td>
              <td>◎</td>
              <td>△</td>
              <td>△</td>
              <td></td>
              <td></td>
              <td></td>
              <td>x</td>
              <td>◎</td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td>△</td>
              <td></td>
              <td></td>
              <td></td>
            </tr>
            <tr>
              <th>Ice</th>
              <td></td>
              <td>△</td>
              <td>△</td>
              <td>◎</td>
              <td></td>
              <td>△</td>
              <td></td>
              <td></td>
              <td>◎</td>
              <td>◎</td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td>◎</td>
              <td></td>
              <td>△</td>
              <td></td>
            </tr>
            <tr>
              <th>Fighting</th>
              <td>◎</td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td>◎</td>
              <td></td>
              <td>△</td>
              <td></td>
              <td>△</td>
              <td>△</td>
              <td>△</td>
              <td>◎</td>
              <td>x</td>
              <td></td>
              <td>◎</td>
              <td>◎</td>
              <td>△</td>
            </tr>
            <tr>
              <th>Poison</th>
              <td></td>
              <td></td>
              <td></td>
              <td>◎</td>
              <td></td>
              <td></td>
              <td></td>
              <td>△</td>
              <td>△</td>
              <td></td>
              <td></td>
              <td></td>
              <td>△</td>
              <td>△</td>
              <td></td>
              <td></td>
              <td>x</td>
              <td>◎</td>
            </tr>
            <tr>
              <th>Ground</th>
              <td></td>
              <td>◎</td>
              <td></td>
              <td>△</td>
              <td>◎</td>
              <td></td>
              <td></td>
              <td>◎</td>
              <td></td>
              <td>x</td>
              <td></td>
              <td>△</td>
              <td>◎</td>
              <td></td>
              <td></td>
              <td></td>
              <td>◎</td>
              <td></td>
            </tr>
            <tr>
              <th>Flying</th>
              <td></td>
              <td></td>
              <td></td>
              <td>◎</td>
              <td>△</td>
              <td></td>
              <td>◎</td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td>◎</td>
              <td>△</td>
              <td></td>
              <td></td>
              <td></td>
              <td>△</td>
              <td></td>
            </tr>
            <tr>
              <th>Psychic</th>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td>◎</td>
              <td>◎</td>
              <td></td>
              <td></td>
              <td>△</td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td>x</td>
              <td>△</td>
              <td></td>
            </tr>
            <tr>
              <th>Bug</th>
              <td></td>
              <td>△</td>
              <td></td>
              <td>◎</td>
              <td></td>
              <td></td>
              <td>△</td>
              <td>△</td>
              <td></td>
              <td>△</td>
              <td>◎</td>
              <td></td>
              <td></td>
              <td>△</td>
              <td></td>
              <td>◎</td>
              <td>△</td>
              <td>△</td>
            </tr>
            <tr>
              <th>Rock</th>
              <td></td>
              <td>◎</td>
              <td></td>
              <td></td>
              <td></td>
              <td>◎</td>
              <td>△</td>
              <td></td>
              <td>△</td>
              <td>◎</td>
              <td></td>
              <td>◎</td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td>△</td>
              <td></td>
            </tr>
            <tr>
              <th>Ghost</th>
              <td>x</td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td>◎</td>
              <td></td>
              <td></td>
              <td>◎</td>
              <td></td>
              <td>△</td>
              <td></td>
            </tr>
            <tr>
              <th>Dragon</th>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td>◎</td>
              <td></td>
              <td>△</td>
              <td>x</td>
            </tr>
            <tr>
              <th>Dark</th>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td>△</td>
              <td></td>
              <td></td>
              <td></td>
              <td>◎</td>
              <td></td>
              <td></td>
              <td>◎</td>
              <td></td>
              <td>△</td>
              <td></td>
              <td>△</td>
            </tr>
            <tr>
              <th>Steel</th>
              <td></td>
              <td>△</td>
              <td>△</td>
              <td></td>
              <td>△</td>
              <td>◎</td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td>◎</td>
              <td></td>
              <td></td>
              <td></td>
              <td>△</td>
              <td>◎</td>
            </tr>
            <tr>
              <th>Fairy</th>
              <td></td>
              <td>△</td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td>◎</td>
              <td>△</td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td>◎</td>
              <td>◎</td>
              <td>△</td>
              <td></td>
            </tr>
          </tbody>
        </table>
      </article>
    </Div>
  )
}

export default TypeEffectivenessContainer

const Div = styled.div`
  width: 100%;
  height: 100%;
`
