import Head from 'next/head'
import styled from 'styled-components'
import { MainViews } from '~/views'

const Main = styled.main`
  width: 100%;
`

export default function Home() {
  return (
    <>
      <Head>
        <title>포켓몬의 모든 정보 포케 코리아</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <MainViews />
      </Main>
    </>
  )
}
